name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - release

jobs:
  main:
    name: Main
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install and build
        run: yarn
      - name: Lint
        run: yarn lint
