name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    name: Main
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install and build
        run: yarn
      - name: Lint
        run: yarn lint
